### PR TITLE
Forward port 3 to 6

### PR DESCRIPTION
**Pull request by nkoenig**
# ➡️ Forward port

Port ign-gui3 to ign-gui6

Branch comparison: https://github.com/gazebosim/gz-gui/compare/ign-gui6...ign-gui3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by iche033** [comment]
> For some reason homebrew CI is having issues finding ignition-math6

probably related: https://github.com/osrf/homebrew-simulation/pull/2206

**Comment by jennuine** [comment]
@osrf-jenkins run tests please

**Review by jennuine — APPROVED** [review]

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by Crola1702** [comment]
> could please look into the GitHub problems for Focal and Jammy and check if they were reported before:

Buildfarmer database doesn't have any record of this test failing

**Comment by scpeters** [comment]
I've made an alternative attempt in https://github.com/gazebosim/gz-gui/pull/533 and we can see if it has the same test failures

**Comment by scpeters** [comment]
it looks like the `ign-gui6` branch already has these failures in the Jammy CI:

* https://github.com/gazebosim/gz-gui/actions/runs/4537672860/jobs/7995762759

**Pull request closed without merging**
