### PR TITLE
ign -> gz CLI Migration : gz-gui

### PR DESCRIPTION
**Pull request by methylDragon**
See: https://github.com/gazebo-tooling/release-tools/issues/739

### CODE REVIEW

**Comment by methylDragon** [comment]
CI failure needs the merge of `gz-tools` so the `gz` executable is available

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please!

**Review by chapulina — CHANGES_REQUESTED** [review]
Ahh `include/ignition/gui/ign.hh` is installed, so we shouldn't move it. I think it's ok to leave it as it is, because it's already deprecated inside the `ignition` folder, and the new `include/gz/gui/gz.hh` header is already correct.

**Comment by methylDragon** [comment]
> Ahh `include/ignition/gui/ign.hh` is installed, so we shouldn't move it. I think it's ok to leave it as it is, because it's already deprecated inside the `ignition` folder, and the new `include/gz/gui/gz.hh` header is already correct.

Fixed! Move no longer occurs in https://github.com/gazebosim/gz-gui/pull/417/commits/a2489b397fbfdc499a3ab9fc5179b8ab78f9e2aa

**Review by chapulina — APPROVED** [review]
`UNIT_gz_TEST` passes on Linux and macOS!

**Pull request merged**
