### PR TITLE
Check for valid pointer

### PR DESCRIPTION
**Pull request by nkoenig**
Signed-off-by: Nate Koenig <nate@openrobotics.org>

# 🦟 Bug fix

## Summary

This is part of an effort to fix the gz-sim UNIT_Gui_TEST. A pointer check has been added to prevent a segfault.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]

**Review by jennuine — COMMENTED** [review]
Can this target `citadel`?

**Comment by nkoenig** [comment]
> Can this target `citadel`?

I'll backport this to `ign-gui6`, the code in citadel doesn't match.

**Comment by jennuine** [comment]
> > Can this target `citadel`?
> 
> I'll backport this to `ign-gui6`, the code in citadel doesn't match.

It doesn't?

`ign-gui3`:
https://github.com/gazebosim/gz-gui/blob/b09d084c737695725f1c6e99b330eeba67b4ea4a/src/Application.cc#L190-L216

`ign-gui7` (w/o your changes):
https://github.com/gazebosim/gz-gui/blob/33adb18fd1922f161f88f74f4a95d06ae1747156/src/Application.cc#L217-L243

**Comment by nkoenig** [comment]
I stand corrected.

**Pull request closed without merging**
