### PR TITLE
Use gz::utils::ImplPtr as much as possible

### PR DESCRIPTION
**Pull request by mjcarroll**
This changes the rest of our `std::unique_ptr` implementations over to `gz::utils::ImplPtr`.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
Windows still not happy

**Comment by mjcarroll** [comment]
Should be fixed by https://github.com/gazebosim/gz-common/pull/553

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by mjcarroll** [comment]
@ahcorde I think we are good here now

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
